### ISSUE TITLE
Add documentation page for webdriver.io website

### ISSUE THREAD

**Issue by christian-bromann** [marcodejongh/chai-webdriverio#11]
Hey @marcodejongh,

would you mind to add your readme to the docs page under plugins: https://github.com/webdriverio/webdriverio/tree/master/docs/guide/plugins ? Just have this on top of your markdown file and the rest similar to what in your readme is:

```
name: chai-webdriverio
category: plugins
tags: guide
index: 3
title: Chai-WebdriverIO
---
```

Thanks

**Comment by marcodejongh** [comment]
Sure I will later today

**Comment by marcodejongh** [comment]
Done https://github.com/webdriverio/webdriverio/pull/1948
