### ISSUE TITLE
Replace the `immediately` flag?

### ISSUE THREAD

**Issue by mltsy** [marcodejongh/chai-webdriverio#13]
I'm not sure the "immediately" flag actually does anything... ??  @christian-bromann has told me (if I understood correctly) that all webdriverio methods that look for elements (`isVisible`, `getText`, etc) will implicitly `waitForExist` until the default timeout expires.  So there's no way to implement a functional `immediately` flag, as I understand it.

We *could* however implement an `eventually` flag that would add some timeout, or maybe even take a timeout as a parameter, and wait for the specified amount of time. (which would follow a recommended practice of setting your default timeout to 0, and waiting as necessary).

Or we could just remove it altogether, and if you need to wait, you can do it explicitly before firing a test :)

**Comment by marcodejongh** [comment]
When was the change added that ```isVisible``` implicitly waits? I wrote that flag a while a go.

I've just checked the webdriverio source and I don't see the implicit wait anywhere, maybe @christian-bromann could clarify? One of the main reasons I wrote this chai plugin was to  prevent me from forgetting to add waits 🤣

**Comment by mltsy** [comment]
Oh noooes!  Haha.  Well, here's the implicit wait setting: http://webdriver.io/guide/testrunner/timeouts.html#Session-Implicit-Wait-Timeout

It says it is used for any calls to `element` or `elements`, and almost every test for a selector does use one of those methods.

I guess one way to accomplish what you were aiming for then, would be to give `chai-webdriverio` a timeout configuration setting, and have it automatically wait for that length of time within `elementExists`, and then the `immediately` flag would skip that wait (and we'd just have to add something to the readme about how the `immediately` flag has no way to skip WDIO's implicit wait, so that should be set to 0 if you want to use `immediately`)

**Comment by mltsy** [comment]
Actually, I kinda like this idea.  And we could have a `within` flag too.  For instance:

```javascript
var chaiWebdriverIO = require('chai-webdriverio').default(browser, {defaultWait: 500});
chai.use(chaiWebdriverIO);
[...]
expect('.save-button').to.immediately.be.there(); // fails immediately if not there
browser.click('.save-button');
expect('.notification').to.be.visible(); // waits up to 500ms by default
expect('.notification').within(2000).to.not.be.visible();
```

**Comment by marcodejongh** [comment]
@mltsy yeah that sounds like a pretty good addition!
