### ISSUE TITLE
Transpile script fails on npm install

### ISSUE THREAD

**Issue by aaronmcadam** [marcodejongh/chai-webdriverio#2]
I've tried to use this directly from GitHub by adding the following to my `package.json`:
`"chai-webdriverio": "git://github.com/marcodejongh/chai-webdriverio.git#master"`

Am I missing something?

When running `npm install`, I get the following output:

``` shell
❯ npm install

> chai-webdriverio@0.0.1 postinstall /path/to/project/node_modules/chai-webdriverio
> npm run transpile

> chai-webdriverio@0.0.1 transpile /path/to/project/node_modules/chai-webdriverio
> babel src -d build

src doesn't exist

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/aaron/.nvm/versions/node/v6.2.0/bin/node" "/Users/aaron/.nvm/versions/node/v6.2.0/bin/npm" "run" "transpile"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! chai-webdriverio@0.0.1 transpile: `babel src -d build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the chai-webdriverio@0.0.1 transpile script 'babel src -d build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chai-webdriverio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src -d build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chai-webdriverio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chai-webdriverio
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/project/node_modules/chai-webdriverio/npm-debug.log
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/aaron/.nvm/versions/node/v6.2.0/bin/node" "/Users/aaron/.nvm/versions/node/v6.2.0/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! chai-webdriverio@0.0.1 postinstall: `npm run transpile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chai-webdriverio@0.0.1 postinstall script 'npm run transpile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chai-webdriverio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run transpile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chai-webdriverio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chai-webdriverio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/project/npm-debug.log
```

**Comment by marcodejongh** [comment]
@aaronmcadam Maybe it should be:

```
"transpile": "node_modules/.bin/babel ./src -d build",
```

It's strange because for me it installs fine, but I'm using a relative install and I assume you are using a git url install? So that would suggest git url installs use a different code path.

 I'll try and see if I can get it published in the coming week that should fix

**Comment by aaronmcadam** [comment]
@marcodejongh Thanks for getting back to me! 

Yeah I heard that we shouldn't have to qualify dependencies with the `node_modules` path. I am indeed using the git url.

Is there anything I can do to help get it published?

**Comment by marcodejongh** [comment]
@aaronmcadam I figured it out, it seems to be related to https://github.com/npm/npm/issues/10366

So you can fix it by either upgrading your version of npm

```
npm i npm@latest -g
```

OR checking out the repo then using a relative directory install and adding this to the postinstall script:

```
npm install --ignore-scripts
```

**Comment by mltsy** [comment]
Yup, looks like this is fixed in latest NPM (v4.4)

**Comment by mltsy** [comment]
Oops!  I spoke too soon.  I'm still getting `src doesn't exist` (even though it got further than before)

**Comment by aaronmcadam** [comment]
Maybe we could look at getting it released, @mitsy.

**Comment by mltsy** [comment]
You mean publishing `chai-webdriverio` to NPM?  Would that fix the installation issue?  I can't see how it would, but I'm pretty new to the Node environment.  If that would fix the issue, I'd look into publishing it.

**Comment by aaronmcadam** [comment]
I'm away from my laptop at the moment. I'll look into this issue and get back to you. I'd like to get this onto NPM with the repo owner's permission of course. I can't remember what the blockers were for not releasing it. I think test coverage was one of the reasons.On 13 Mar 2017 7:08 pm, Joe Marty <notifications@github.com> wrote:You mean publishing chai-webdriverio to NPM?  Would that fix the installation issue?  I can't see how it would, but I'm pretty new to the Node environment.  If that would fix the issue, I'd look into publishing it.

**Comment by mltsy** [comment]
Cool.  I mean I would love to get it into NPM of course (maybe you saw the other issue I put in for that) :wink:

I also just noticed that even moving the dependency from `devDependencies` to `dependencies` doesn't fix the issue for me, so I think the problem may be unrelated to the NPM bug mentioned above.  I have it in my **package.json** as:

```javascript
dependencies: {
  ...,
  "chai-webdriverio": "git+https://github.com/marcodejongh/chai-webdriverio.git"
}
```

and I'm still getting `src  doesn't exist` with the following in the log output:
```
146 silly postinstall chai-webdriverio@0.0.1
147 info lifecycle chai-webdriverio@0.0.1~postinstall: chai-webdriverio@0.0.1
148 verbose lifecycle chai-webdriverio@0.0.1~postinstall: unsafe-perm in lifecycle true
149 verbose lifecycle chai-webdriverio@0.0.1~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/jmarty/Projects/dash
board/node_modules/chai-webdriverio/node_modules/.bin:/home/jmarty/Projects/dashboard/node_modules/.bin:[...]
150 verbose lifecycle chai-webdriverio@0.0.1~postinstall: CWD: /home/jmarty/Projects/dashboard/node_modules/chai-webdriverio
151 silly lifecycle chai-webdriverio@0.0.1~postinstall: Args: [ '-c', 'npm run transpile' ]
152 silly lifecycle chai-webdriverio@0.0.1~postinstall: Returned: code: 2  signal: null
153 info lifecycle chai-webdriverio@0.0.1~postinstall: Failed to exec postinstall script
```

Earlier in the log, it extracts files into `node_modules/.staging/chai-webdriver-io-[SHA]`, and then deletes them, but never mentions extracting or copying anything to `node_modules/chai-webdriver` so I'm wondering if some path is specified wrong?

**Comment by marcodejongh** [comment]
@mitsy Sorry was a bit away from github, I'll try to address you issues tomorrow morning

**Comment by marcodejongh** [comment]
@mltsy Is this still a issue now that it's published to npm? I could change it to prepublish generate the dist folder

**Comment by aaronmcadam** [comment]
@marcodejongh I've confirmed the package now transpiles and tests pass for me locally. Thanks! Closing...

**Comment by aaronmcadam** [comment]
> I could change it to prepublish generate the dist folder

@marcodejongh [I've raised a PR for that](https://github.com/marcodejongh/chai-webdriverio/pull/6)

**Comment by mltsy** [comment]
Ooh, didn't transpile for me, because I don't have yarn installed :)  But getting the transpiled version published on npm should take care of that!
