### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by mltsy** [marcodejongh/chai-webdriverio#4]
Awesome work!  Just curious if you plan to publish this on NPM.  I'd use it! (But I don't want to tie my project to a package from a personal repo that's not published on npm)

**Comment by mltsy** [comment]
I see this (or a similar thing) has been published! :)

https://www.npmjs.com/package/chai-webdriver

http://chaijs.com/plugins/chai-webdriver/

**Comment by mltsy** [comment]
Oh, nevermind, that one doesn't work with webdriverio I guess.

**Comment by marcodejongh** [comment]
@mitsy chai-webdriver is a seperate package that uses the raw webdriver api if I remember correctly.
Anyhow I've published the module here: https://www.npmjs.com/package/chai-webdriverio

**Comment by aaronmcadam** [comment]
Thanks @marcodejongh! :heart:

**Comment by mltsy** [comment]
YES! :smile:  :+1: :champagne:

**Comment by christian-bromann** [comment]
Let's close this one then
