### ISSUE TITLE
Make chai-webdriverio compatible with WebdriverIO v5

### ISSUE THREAD

**Issue by AnnikaNissen** [marcodejongh/chai-webdriverio#48]
The new version 5 of WebdriverIO contains a lot of breaking changes, so that this chai plugin no longer is compatible. It would be really awesome, if this plugin would be updated to work with WebdriverIO v5.

The changelog for WebdriverIO v5 can be found [here](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#v500-2018-12-20).

**Comment by AnnikaNissen** [comment]
I'm working on a fix and will create a pull request shortly.

**Comment by xlenz** [comment]
@AnnikaNissen can this one be closed?

**Comment by AnnikaNissen** [comment]
Yes :)
