### ISSUE TITLE
chai-webdriverio throws an exception anytime an expect clause with displayed is fired

### ISSUE THREAD

**Issue by rpii** [marcodejongh/chai-webdriverio#51]
I am trying to port over to using the new chai-webdriverio.  I am getting exceptions with the assertion functions in this package.  I have created a demo here:

https://github.com/rpii/wdio-test

it blows up on simple test case.  from the readme in the readme.md for the above project:

I am using the newly updated chai-webdriverio assertions library v 1.0.0.

the code at line of basic.test.spec.js: ... expect(title, 'WebdriverIO · Next-gen WebDriver test framework for Node.js').to.be.displayed();

causes an error to be thrown deep into the hook callbacks.

This is the stack you see, but there is another exception stack that gets covered up

Error: selector needs to be typeof string or function at Object. (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules@wdio\runner\node_modules\webdriverio\build\utils.js:39:32) at Module._compile (internal/modules/cjs/loader.js:738:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10) at Module.load (internal/modules/cjs/loader.js:630:32) at tryModuleLoad (internal/modules/cjs/loader.js:570:12) at Function.Module._load (internal/modules/cjs/loader.js:562:3) at Module.require (internal/modules/cjs/loader.js:667:17) at require (internal/modules/cjs/helpers.js:20:18) at Object. (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules@wdio\runner\node_modules\webdriverio\build\multiremote.js:16:14) at Browser.runCommand (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules@wdio\sync\build\wrapCommand.js:31:24) at Browser. (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules@wdio\sync\build\wrapCommand.js:53:31) at isOneElementDisplayed (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules\chai-webdriverio\dist\assertions\displayed.js:15:27) at Browser. (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules\chai-webdriverio\dist\assertions\displayed.js:36:24) at C:\Users\rpeter\Development\automated-test\wdio-test\node_modules@wdio\sync\build\runFnInFiberContext.js:20:25

it starts from client$$(selector) in the code below:

var isOneElementDisplayed = function isOneElementDisplayed(client, selector) {
    var elements = client.$$(selector);
    var filteredList = elements.filter(function (element) {
        return element.isDisplayed();
    });

    return filteredList.length > 0;
};

...

Anyone have any ideas?

**Comment by mltsy** [comment]
Yeah!  There shouldn't be two arguments passed to `expect`, and the argument (the selector) should be a string 😄  I think what you might be after is:

```js
expect('//h2[@class="projectTitle"]').to.have.text('WebdriverIO · Next-gen WebDriver test framework for Node.js');
```
Or perhaps
```js
expect('//h2[@class="projectTitle"]=WebdriverIO · Next-gen WebDriver test framework for Node.js').to.be.displayed();
```

Although I'm not totally sure of the selector syntax on that last one... See https://webdriver.io/docs/selectors.html#element-with-certain-text for selector help :)

**Comment by rpii** [comment]
Joe,

My sample is a little bit confusing and changed from the original sample.
I was using the second argument to expect as the textual error message for expect.  I was just looking for the selector to be displayed on the screen.  I tried a few more permutations

            expect(title, 'WebdriverIO · Next-gen WebDriver test framework for Node.js').to.be.displayed();
            expect(title).to.be.displayed();
            expect(title).to.have.text('WebdriverIO · Next-gen WebDriver test framework for Node.js');
to.be.displayed();

All gave the  mentioned stack trace

Trying to.be.there gave a different result it seems to take a different path:

[chrome #0-0] 1) webdriver.io page should have the right title
[chrome #0-0] Expected <[object Object]> to be there, but it is not there.
[chrome #0-0] AssertionError: Expected <[object Object]> to be there, but it is not there.
[chrome #0-0]     at Context.there (C:\Users\rpeter\Development\automated-test\wdio-test\test\specs/basic.test.spec.js:11:33)
[chrome #0-0]     at Promise (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules\@wdio\sync\build\index.js:58:22)
[chrome #0-0]     at Context.executeSync (C:\Users\rpeter\Development\automated-test\wdio-test\node_modules\@wdio\sync\build\index.js:56:10)
[chrome #0-0]     at C:\Users\rpeter\Development\automated-test\wdio-test\node_modules\@wdio\sync\build\index.js:202:70

Rich

**Comment by mltsy** [comment]
Okay, yeah your first argument there still isn't a string.  I could be wrong, but I think that's the main problem.  `title` needs to be the selector string, not an element, or whatever `$('...')` returns.

**Comment by rpii** [comment]
Well you are correct.  
I was using the selectors that you use for selectors in page objects.  
ie: https://webdriver.io/docs/selectors.html

 since I plan to use those extensively. those all have $() syntax

Wish there was a way to reuse those. kind of inconvenient to have two types of syntax.

anyway thanks so much... that  moves me forward quite a bit!!!

**Comment by mltsy** [comment]
No problem!  Just to clarify, those are the same selectors - the selector is the string - it's just that `$(...)` is a webdriverio function that applies the selector and returns a webdriverio element object that you can call methods on, etc.  In the case of this package, `expect` is a similar function - you need to give it a selector (rather than an element) so that it can use the selector as appropriate to find a the element or elements necessary, depending on the use case (or no elements, in the case of `expect('...').to.not.be.there`)
