### ISSUE TITLE
Readme missing `.dom` in a few places

### ISSUE THREAD

**Issue by mltsy** [marcodejongh/chai-webdriverio#7]
I'd be happy to submit a PR for this if you can confirm that I'm right about this being an issue.  It looks like the Readme has several examples that are missing the `.dom` flag, which I believe is required... is that right?

**Comment by christian-bromann** [comment]
Yes a PR would be great, thanks!

**Comment by mltsy** [comment]
Oh wait though... all the tests appear to not use the `.dom` flag... (I haven't successfully used the library yet, so I wasn't sure whether it was required or not, was just going odd of the readme) - so... apparently it's *not* required?  If that's the case, I'll remove it from the Readme... I actually don't see the text `dom` anywhere in the code other than the readme and a couple exception strings, so I will conclude from that that it's not used or required! :)
